[package]
name = "hideout"
version = "0.1.0"
authors = ["inkyu <gofiri@gmail.com>"]
edition = "2018"

[dependencies]
dope = {git = "https://github.com/inq/dope"}

futures = "*"
chrono = "*"
color-backtrace = { version = "*", features = ["failure-bt"] }
failure = "*"
log = "*"
nom = "*"