[package]
name = "hideout"
version = "0.1.0"
authors = ["inkyu <gofiri@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "*"
chrono = "*"
failure = "*"
futures = "*"
httparse = "*"
log = "*"
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
tokio = { version = "*", features = ["io-util", "macros", "rt-core", "stream", "tcp"] }
tokio-postgres = "*"
